#!/bin/bash

for i in {30..0}; do
  if [ -d "/var/lib/mysql/hivelocity" ]; then
    break
  fi
  echo 'MySQL init process in progress...'
  sleep 1
done

if [ "$i" = 0 ]; then
  echo >&2 'MySQL init process failed.'
  exit 1
fi

MYSQL_PWD='hivelocity' /usr/bin/mysql -uroot hivelocity < /databases/hivelocity-local.sql
echo "===> Created tables"
